162633510 Ft tag articles
andela/ah-backend-valkyrie pull request #21
Opened 2019-01-23 15:10 UTC by mubstimor

### What does this PR do?
* Enable authors to add tags to their articles

#### Tasks to be completed
* Add tags to articles being created

#### How should this be manually tested.
* Add an array of strings for variable tagList to create article request
e.g. `"tagList": ["test1", "test2", "Tag3"]`

#### What are the relevant pivotal tracker stories?
Delivers [162633510](https://www.pivotaltracker.com/story/show/162633510)

2019-01-24 11:35 UTC, jeanjoe submitted a review, later dismissed

2019-01-24 11:35 UTC, jeanjoe commented on authors/apps/articles/urls.py
> +    path('author/<str:username>/', RetrieveAuthorArticles.as_view(), name="author_articles"),
Reduce this line to less than 80 characters

2019-01-24 11:35 UTC, jeanjoe commented on authors/apps/articles/admin.py
> +# class TagInline(admin.TabularInline):
Remove commented code not useful

2019-01-24 11:35 UTC, jeanjoe commented on authors/apps/articles/renderers.py
> +
Also remove extra line from your work

2019-01-24 11:35 UTC, jeanjoe commented on authors/apps/articles/serializers.py
> +    # author = ProfileSerializer(read_only=True)
remove this commented line of code

2019-01-25 08:55 UTC, jeanjoe commented
LGTM

2019-01-25 09:02 UTC, jeanjoe requested changes

2019-01-25 09:02 UTC, jeanjoe commented on authors/apps/articles/tests/test_articles.py
> +from pprint import pprint
Remove this unused import

2019-01-25 09:11 UTC, jeanjoe approved these changes

2019-01-25 09:12 UTC, jeanjoe commented
LGTM

2019-01-25 09:43 UTC, NabunyaLilian commented
LGTM

2019-01-25 09:44 UTC, NabunyaLilian commented
Though you should reduce the number of your commits to one

2019-01-25 09:45 UTC, NabunyaLilian commented on authors/apps/articles/admin.py
> +admin.site.register(Tag)
please add a new line

2019-01-28 14:56 UTC, jeanjoe requested changes

2019-01-28 14:56 UTC, jeanjoe commented on authors/apps/articles/serializers.py
>  from .models import Article, FavoriteArticle
Please keep all the imports at the top

2019-01-28 15:19 UTC, jeanjoe submitted a review, later dismissed

2019-01-28 15:19 UTC, jeanjoe commented on authors/apps/articles/serializers.py
> +        tag = validated_data['tagList']
Please remove unused variable

2019-01-28 15:19 UTC, jeanjoe commented on authors/apps/articles/serializers.py
> +        return tag[0].id
Please return an object to avoid data obstruction.

2019-01-29 14:22 UTC, Qadriyah commented
LGTM

2019-01-29 14:22 UTC, mycok commented
LGTM

2019-01-29 14:23 UTC, fatukunda commented
LGTM

2019-01-29 17:48 UTC, merged

2019-02-01 15:17 UTC, mubstimor commented
> Though you should reduce the number of your commits to one

noted, thank you!